INSERT INTO PROV_USERS VALUES (0, 'Roman', 'Khrapko', 'CUSTOMER', '900.0');
INSERT INTO PROV_USERS (ID, NAME, SURNAME, TYPE) VALUES (1, 'Nikita', 'Krasnopolskiy', 'EMPLOYEE' );
INSERT INTO PROV_USERS VALUES (2, 'Anna', 'Nosova', 'CUSTOMER', '2900.0');
INSERT INTO PROV_USERS (ID, NAME, SURNAME, TYPE) VALUES (3, 'Ilya', 'Golovin', 'EMPLOYEE' );

INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (0, 'Internet50', 0, TO_DATE('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);
INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (1, 'Internet50', 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);
INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (2, 'InternetVIP', 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);
INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (3, 'Internet100', 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);
INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (4, 'Internet50', 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);
INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (5, 'Internet50', 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);
INSERT INTO PROV_INSTANCES (ID, TEMPLATE, CUSTOMER_ID, CONNECTION_DATE, INSTANCE_STATUS, DELTA) VALUES (6, 'InternetVIP', 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'ACTIVE', 0);

INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (0, 0, 1, 'Internet50', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, INSTANCE_ID, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (1, 0, 1, 0, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'SUSPEND');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (2, 0, 1, 'Internet50', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (3, 0, 1, 'InternetVIP', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (4, 0, 1, 'Internet100', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (5, 0, 1, 'Internet50', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (6, 0, 1, 'Internet50', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, EMPLOYEE_ID, TEMPLATE, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (7, 0, 1, 'InternetVIP', TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'COMPLETE', 'CONNECT');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, INSTANCE_ID, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (8, 0, 0,TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'NOT_STARTED', 'SUSPEND');
INSERT INTO PROV_ORDERS (ID, CUSTOMER_ID, INSTANCE_ID, REQUEST_DATE, ORDER_STATUS, ORDER_ACTION) VALUES (9, 0, 4, TO_DATE ('2016.05.12', 'YYYY-MM-DD'), 'NOT_STARTED', 'SUSPEND');
